[package]
name = "get"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.26"
tokio ={ version="1.36.0" , features=["full"]}
soup="0.5.1"
clap={version="4.5.3", features=["derive"]}


